#!/usr/bin/env bash
# Writes .env with the address WSL uses to reach services on the Windows host.
#
# TrueForge runs inside WSL; the Placebo MCP server and Roblox Studio run on
# Windows. They meet over the WSL default gateway, whose address changes across
# reboots, so it is detected rather than pinned.
#
# Two things this got wrong before, both worth keeping fixed:
#   - do not hardcode a distro name (this machine's is Ubuntu, the training
#     rig's is Ubuntu-24.04), and
#   - do not run the probe under `pipefail`: wsl.exe can exit non-zero while
#     still having printed the route, which silently produced an empty gateway.
set -uo pipefail
cd "$(dirname "$0")/.."

ROUTE=$(wsl.exe -- ip route show default 2>/dev/null | tr -d '\0\r' || true)
GATEWAY=$(printf '%s\n' "$ROUTE" | awk '{print $3; exit}')

if [ -z "${GATEWAY}" ]; then
  echo "could not determine the WSL default gateway (route was: '${ROUTE}')" >&2
  exit 1
fi

cat > .env <<ENVFILE
# Generated by scripts/detect-env.sh — re-run after a reboot.
TRUEFORGE_BASE_URL=http://localhost:8790
PLACEBO_MCP_HOST=http://${GATEWAY}:9400
ENVFILE

echo "wrote .env (PLACEBO_MCP_HOST=http://${GATEWAY}:9400)"
